# Generated by Django 6.0.7 on 2026-08-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membresia_usuario_rol_usuario_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itempauta',
            options={'ordering': ['orden', 'texto']},
        ),
        migrations.AddField(
            model_name='itempauta',
            name='obligatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itempauta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempauta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itempauta',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pauta'),
        ),
        migrations.AlterField(
            model_name='itempauta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itempauta',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tipoitempauta'),
        ),
        migrations.CreateModel(
            name='CampoPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='core.pauta')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='itempauta',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.campopauta'),
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=150)),
                ('valor', models.IntegerField(default=0)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.itempauta')),
            ],
            options={
                'ordering': ['orden', 'valor'],
            },
        ),
        migrations.AddField(
            model_name='itempauta',
            name='tipo_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.tiporespuesta'),
        ),
    ]
