# Generated by Django 6.0.7 on 2026-08-16 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tiporespuesta_alter_itempauta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('edad_min', models.PositiveIntegerField(default=0)),
                ('edad_max', models.PositiveIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='core.pauta')),
            ],
            options={
                'ordering': ['edad_min', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='campopauta',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='core.versionpauta'),
        ),
        migrations.AddField(
            model_name='itempauta',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.versionpauta'),
        ),
    ]
