# Generated by Django 6.0.7 on 2026-08-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_versionpauta_campopauta_version_itempauta_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='core.versionpauta'),
        ),
        migrations.AddField(
            model_name='itempauta',
            name='modo_puntuacion',
            field=models.CharField(choices=[('automatico', 'Automático según respuesta'), ('sin_puntaje', 'No puntuar este ítem'), ('valor_directo', 'Usar el número respondido como puntaje'), ('opciones', 'Usar puntajes de las opciones')], default='automatico', max_length=20),
        ),
        migrations.AddField(
            model_name='pauta',
            name='modo_puntuacion',
            field=models.CharField(choices=[('general', 'Puntaje general'), ('por_campo', 'Puntaje por campo'), ('sin_puntaje', 'Sin puntuación')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='versionpauta',
            name='modo_puntuacion',
            field=models.CharField(choices=[('heredar', 'Usar configuración de la pauta'), ('general', 'Puntaje general'), ('por_campo', 'Puntaje por campo'), ('sin_puntaje', 'Sin puntuación')], default='heredar', max_length=20),
        ),
        migrations.CreateModel(
            name='ReglaTabulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_minimo', models.IntegerField()),
                ('puntaje_maximo', models.IntegerField()),
                ('etiqueta', models.CharField(max_length=120)),
                ('interpretacion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_tabulacion', to='core.campopauta')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_tabulacion', to='core.pauta')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_tabulacion', to='core.versionpauta')),
            ],
            options={
                'ordering': ['orden', 'puntaje_minimo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('puntaje_maximo', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=120)),
                ('interpretacion', models.TextField(blank=True)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='core.campopauta')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_campos', to='core.evaluacion')),
            ],
            options={
                'ordering': ['campo__orden', 'campo__nombre'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'campo'), name='unique_resultado_campo_evaluacion')],
            },
        ),
    ]
