# Generated by Django 6.0.7 on 2026-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evaluacion_version_itempauta_modo_puntuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='pautas_multiples', to='core.categoriapauta'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='edad_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='edad_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
