# Generated by Django 6.0.7 on 2026-09-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_telefono_reportes_issues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportes_issues',
            options={'ordering': ['-fecha_reporte']},
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_issues', to='core.campopauta'),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_issues', to='core.itempauta'),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_issues', to='core.pauta'),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='respuesta_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='url_pagina',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='reportes_issues',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_issues', to='core.versionpauta'),
        ),
    ]
