# Generated by Django 6.0.7 on 2026-09-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reportes_issues_options_reportes_issues_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
