# Generated by Django 6.0.7 on 2026-09-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paciente_edad_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='terapeuta',
        ),
    ]
