# Generated by Django 6.0.7 on 2026-09-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_paciente_terapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
