# Generated by Django 6.0.7 on 2026-09-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_paciente_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
    ]
